---
spring:
  profiles: default

logging:
  level:
    org.springframework.boot: DEBUG
env1: default
---
spring:
  profiles: prod
logging:
  level:
    org.springframework.boot: DEBUG
env2: production
